using UnityEngine;

/// <summary>
/// Presentation layer for the player's animations. Listens to the FSM's state changes and
/// cross-fades the Animator to the matching state; every tick it feeds the locomotion blend
/// tree with the current speed. States never talk to the Animator (docs/features.md §4.4).
///
/// The FSM is the single source of truth: the Animator Controller has almost no transitions of
/// its own (only chained one-shots that return to a loop: Block enter/exit, Land, Ledge hang),
/// so the two can never disagree. Root motion is off — the Rigidbody is moved by the states (D1).
/// The controller is generated by Tools → Warrior Woke → Configurar Animaciones del Jugador.
/// </summary>
[RequireComponent(typeof(PlayerMovement))]
public class PlayerAnimator : MonoBehaviour
{
    [Tooltip("Animator on the visual model. Found in children if left empty.")]
    [SerializeField] private Animator animator;

    [Tooltip("Default cross-fade time (seconds) between animation states.")]
    [SerializeField] private float crossFadeTime = 0.15f;

    [Tooltip("Cross-fade time (seconds) into attacks and landings, kept short so they read as snappy.")]
    [SerializeField] private float fastCrossFadeTime = 0.05f;

    [Tooltip("Damping (seconds) applied to the Speed parameter.")]
    [SerializeField] private float speedDampTime = 0.1f;

    [Tooltip("Falls shorter than this (seconds) land straight into locomotion, without a landing animation.")]
    [SerializeField] private float minFallTimeForLanding = 0.35f;

    private PlayerMovement _movement;
    private PlayerState    _previousState;
    private float          _fallStartTime;

    // ─── Lifecycle ───────────────────────────────────────────────────────────────

    private void Awake()
    {
        _movement = GetComponent<PlayerMovement>();
        if (animator == null)
            animator = GetComponentInChildren<Animator>();

        if (animator == null)
        {
            Debug.LogWarning("[PlayerAnimator] No Animator found on the player model; animations are disabled.");
            return;
        }

        animator.applyRootMotion = false;

        // OnAnimatorIK is only sent to the Animator's own GameObject, so a relay forwards it here.
        var relay = animator.GetComponent<PlayerAnimatorIK>();
        if (relay != null) relay.Owner = this;
    }

    private void OnEnable()
    {
        _movement.StateChanged += HandleStateChanged;
    }

    private void OnDisable()
    {
        _movement.StateChanged -= HandleStateChanged;
    }

    private void Update()
    {
        if (animator == null || _movement.Rb == null) return;

        // Signed and normalized: speed along the facing direction / BaseSpeed. Negative while
        // walking backward (backpedal), 1 = run, SprintMultiplier = sprint. Using the facing
        // keeps the blend thresholds valid if BaseSpeed is tuned.
        Vector3 velocity = _movement.Rb.linearVelocity;
        Vector3 horizontal = new Vector3(velocity.x, 0f, velocity.z);
        float forwardSpeed = Vector3.Dot(horizontal, transform.forward);
        float speed = forwardSpeed < -0.05f ? forwardSpeed : horizontal.magnitude;
        float normalizedSpeed = _movement.BaseSpeed > 0f ? speed / _movement.BaseSpeed : 0f;
        animator.SetFloat(PlayerAnimatorIds.SpeedParam, normalizedSpeed, speedDampTime, Time.deltaTime);
    }

    // ─── State → Animation ───────────────────────────────────────────────────────

    private void HandleStateChanged(PlayerState state)
    {
        if (animator == null) return;

        if (state == _movement.FallState)
            _fallStartTime = Time.time;

        int target = ResolveAnimatorState(state, out bool fast);
        _previousState = state;

        if (target != 0)
            animator.CrossFadeInFixedTime(target, fast ? fastCrossFadeTime : crossFadeTime);
    }

    private int ResolveAnimatorState(PlayerState state, out bool fast)
    {
        var m = _movement;
        fast = false;

        if (state == m.IdleState || state == m.RunState)
        {
            // Leaving the guard plays the Ch45 "fight idle → standing idle" transition first
            if (_previousState == m.BlockState) return PlayerAnimatorIds.BlockExit;

            // Landing after a real fall (visual only: control is never blocked)
            if (_previousState == m.FallState && Time.time - _fallStartTime >= minFallTimeForLanding)
            {
                fast = true;
                return state == m.RunState ? PlayerAnimatorIds.LandRun : PlayerAnimatorIds.Land;
            }

            return PlayerAnimatorIds.Locomotion;
        }

        if (state == m.JumpState)        return PlayerAnimatorIds.Jump;
        if (state == m.FallState)        return PlayerAnimatorIds.Fall;
        if (state == m.SlideState)       { fast = true; return PlayerAnimatorIds.Slide; }
        if (state == m.VaultState)       { fast = true; return PlayerAnimatorIds.Vault; }
        if (state == m.LedgeGrabState)   { fast = true; return PlayerAnimatorIds.LedgeGrab; }
        if (state == m.LedgeClimbState)  return PlayerAnimatorIds.LedgeClimb;
        if (state == m.HeavyAttackState) { fast = true; return PlayerAnimatorIds.HeavyAttack; }
        if (state == m.BlockState)       return PlayerAnimatorIds.BlockEnter;

        if (state == m.LightAttackState)
        {
            // Alternate fists along the combo: right, left, right
            fast = true;
            return m.LightAttackState.ChainIndex % 2 == 1 ? PlayerAnimatorIds.LightAttackRight : PlayerAnimatorIds.LightAttackLeft;
        }

        if (state == m.DodgeState)
        {
            Vector2 dir = m.DodgeState.LocalDirection;
            animator.SetFloat(PlayerAnimatorIds.DodgeXParam, dir.x);
            animator.SetFloat(PlayerAnimatorIds.DodgeYParam, dir.y);
            fast = true;
            return PlayerAnimatorIds.Dodge;
        }

        return 0;
    }

    // ─── IK (called by PlayerAnimatorIK on the model) ────────────────────────────

    /// <summary>
    /// Vault hand IK (from Dynamic Parkour System's VaultObstacle): pins the left hand on the
    /// obstacle's top, weighted by the "LHandCurve" curve of the VaultFence clip.
    /// </summary>
    public void ApplyIK()
    {
        if (animator == null) return;

        if (_movement.StateMachine.CurrentState != _movement.VaultState)
        {
            animator.SetIKPositionWeight(AvatarIKGoal.LeftHand, 0f);
            animator.SetIKRotationWeight(AvatarIKGoal.LeftHand, 0f);
            return;
        }

        float weight = Mathf.Clamp01(animator.GetFloat(PlayerAnimatorIds.LHandCurveParam));
        animator.SetIKPositionWeight(AvatarIKGoal.LeftHand, weight);
        animator.SetIKRotationWeight(AvatarIKGoal.LeftHand, weight);
        animator.SetIKPosition(AvatarIKGoal.LeftHand, _movement.VaultState.HandTarget);
        animator.SetIKRotation(AvatarIKGoal.LeftHand, _movement.VaultState.HandRotation);
    }
}
