using UnityEngine;

/// <summary>
/// Presentation layer for the player's animations. Listens to the FSM's state changes and
/// cross-fades the Animator to the matching state; every tick it feeds the locomotion blend
/// tree with the current speed. States never talk to the Animator (docs/features.md §4.4).
///
/// The FSM is the single source of truth: the Animator Controller has almost no transitions of
/// its own (only chained one-shots that return to a loop: Block enter/exit, landings, Ledge hang),
/// so the two can never disagree. Locomotion clips play in place; in Idle and Run motion matching
/// (PlayerMxMLocomotion, P29) blends over the controller and its root motion moves the body; the
/// other states are moved by their velocity. Parkour actions use root motion (P22): the vault's clip
/// time goes to PlayerVaultState, which warps the clip's measured path onto the obstacle (P36); during LedgeGrab, LedgeClimb,
/// Mantle and LedgeDrop it is forwarded to PlayerMovement and warped with Animator.MatchTarget so hands
/// and feet arrive on the contact points measured by EnvironmentChecker; PlayerContactIK then keeps
/// them there. Parkour states read the clip's progress through IParkourAnimationProgress.
/// Attacks and hit reactions (P37) read theirs through ICombatAnimation, which also freezes the
/// Animator for a hit stop; an attack's own step (its root motion) goes to the motor, and on the final
/// pose of every frame the striking limb sweeps for targets (PlayerAttackState.Sweep).
/// The controller is generated by Tools → Warrior Woke → Configurar Animaciones del Jugador.
/// </summary>
[RequireComponent(typeof(PlayerMovement))]
public class PlayerAnimator : MonoBehaviour, IParkourAnimationProgress, ICombatAnimation
{
    [Tooltip("Animator on the visual model. Found in children if left empty.")]
    [SerializeField] private Animator animator;

    [Tooltip("Default cross-fade time (seconds) between animation states.")]
    [SerializeField] private float crossFadeTime = 0.2f;

    [Tooltip("Cross-fade time (seconds) into attacks, landings and parkour actions, kept short so contacts line up.")]
    [SerializeField] private float fastCrossFadeTime = 0.08f;

    [Tooltip("Cross-fade time (seconds) into the fall loop: the body eases into the air pose.")]
    [SerializeField] private float fallCrossFadeTime = 0.3f;

    [Tooltip("Damping (seconds) applied to the MoveX/MoveZ parameters.")]
    [SerializeField] private float speedDampTime = 0.1f;

    [Tooltip("Measured ground speed (m/s) of the fastest locomotion clip (Run). Faster than this, the locomotion plays faster instead of sliding. Written by PlayerAnimationSetup from ClipMeasurement.")]
    [SerializeField] private float fastestClipSpeed = 5.9f;

    [Tooltip("Time (seconds) the model takes to catch up with the body after an auto step lifts it.")]
    [SerializeField] private float stepSmoothTime = 0.1f;

    [Tooltip("Degrees per second the body turns to square up with the obstacle or wall during a parkour action.")]
    [SerializeField] private float parkourTurnSpeed = 540f;

    [Header("Posture (weight and momentum)")]
    [Tooltip("Fraction of the physical lean (atan of acceleration / g) the torso shows. 0 disables the lean.")]
    [SerializeField] private float leanAmount = 0.6f;
    [Tooltip("Largest sideways lean into a turn (degrees).")]
    [SerializeField] private float maxLeanRoll = 10f;
    [Tooltip("Largest forward lean when accelerating / backward lean when braking (degrees).")]
    [SerializeField] private float maxLeanForward = 8f, maxLeanBack = 6f;
    [Tooltip("Seconds the lean takes to settle.")]
    [SerializeField] private float leanSmoothTime = 0.15f;

    private PlayerMovement  _movement;
    private PlayerContactIK _contactIK;
    private PlayerState     _previousState;
    private Transform       _model;
    private Vector3         _modelBaseLocalPosition;
    private float           _rootAboveFeet;   // model root height above the collider bottom
    private float           _stepOffset;
    private float           _stepVelocity;
    private int             _parkourStateHash;
    private int             _actionStateHash;   // the attack or hit reaction playing (ICombatAnimation)
    private bool            _actionPending;     // its cross-fade is requested but the Animator has not run it yet
    private float           _hitStopUntil = -1f;
    private int             _matchPhase;
    private float           _grabClipLength  = 1f;
    private float           _vaultLength = 1f;   // the playing vault clip (VaultCatalog)
    private Transform       _spine, _chest, _footL, _footR, _armL, _armR, _handL, _handR, _kneeL, _kneeR, _toeL, _toeR, _head;
    private int             _groundMask;
    private float           _lastYaw, _lastForwardSpeed, _yawRate, _forwardAccel, _forwardSpeed;
    private float           _roll, _pitch, _rollVel, _pitchVel, _leanWeight, _leanWeightVel;

    // ─── Lifecycle ───────────────────────────────────────────────────────────────

    private void Awake()
    {
        _movement  = GetComponent<PlayerMovement>();
        _contactIK = GetComponent<PlayerContactIK>();
        if (animator == null)
            animator = GetComponentInChildren<Animator>();

        if (animator == null)
        {
            Debug.LogWarning("[PlayerAnimator] No Animator found on the player model; animations are disabled.");
            return;
        }

        // The motor reads the root motion every frame (motion matching); OnAnimatorMove exists, so
        // Unity never applies it by itself
        animator.applyRootMotion = true;
        animator.cullingMode = AnimatorCullingMode.AlwaysAnimate; // root motion and IK also off screen
        _model = animator.transform;
        _modelBaseLocalPosition = _model.localPosition;
        var body = GetComponent<CharacterController>();
        _rootAboveFeet = _modelBaseLocalPosition.y + (body != null ? body.height * 0.5f - body.center.y + body.skinWidth : 0f);

        foreach (AnimationClip clip in animator.runtimeAnimatorController.animationClips)
        {
            if (clip.name == PlayerAnimatorIds.LedgeGrabClip) _grabClipLength = clip.length;
        }
        if (animator.isHuman)
        {
            _spine = animator.GetBoneTransform(HumanBodyBones.Spine);
            _chest = animator.GetBoneTransform(HumanBodyBones.Chest);
            _footL = animator.GetBoneTransform(HumanBodyBones.LeftFoot);
            _footR = animator.GetBoneTransform(HumanBodyBones.RightFoot);
            _armL  = animator.GetBoneTransform(HumanBodyBones.LeftUpperArm);
            _armR  = animator.GetBoneTransform(HumanBodyBones.RightUpperArm);
            _handL = animator.GetBoneTransform(HumanBodyBones.LeftHand);
            _handR = animator.GetBoneTransform(HumanBodyBones.RightHand);
            _kneeL = animator.GetBoneTransform(HumanBodyBones.LeftLowerLeg);
            _kneeR = animator.GetBoneTransform(HumanBodyBones.RightLowerLeg);
            _toeL  = animator.GetBoneTransform(HumanBodyBones.LeftToes);
            _toeR  = animator.GetBoneTransform(HumanBodyBones.RightToes);
            _head  = animator.GetBoneTransform(HumanBodyBones.Head);
            _groundMask = LayerMask.GetMask("Ground", "Obstacle");
        }
        _lastYaw = transform.eulerAngles.y;

        // OnAnimatorIK and OnAnimatorMove are only sent to the Animator's own GameObject, so a relay forwards them here.
        var relay = animator.GetComponent<PlayerAnimatorIK>();
        if (relay != null)
        {
            relay.Owner = this;
            relay.Movement = _movement;
        }

        _movement.ParkourAnimation = this;
        _movement.CombatAnimation = this;
    }

    private void OnEnable()
    {
        _movement.StateChanged += HandleStateChanged;
        _movement.Stepped      += HandleStepped;
    }

    private void OnDisable()
    {
        _movement.StateChanged -= HandleStateChanged;
        _movement.Stepped      -= HandleStepped;
    }

    private void Update()
    {
        if (animator == null) return;

        // The directional blend reads the real velocity under the body (m/s, local right/forward):
        // walking forward, backward, strafing or in a diagonal picks the clips whose measured pace and
        // direction match. Beyond the fastest clip (a sprint), the locomotion plays faster instead.
        // (Under motion matching it only shows while MxM fades in or out.)
        Vector3 velocity = _movement.Velocity;
        Vector3 local = transform.InverseTransformDirection(new Vector3(velocity.x, 0f, velocity.z));
        animator.SetFloat(PlayerAnimatorIds.MoveXParam, local.x, speedDampTime, Time.deltaTime);
        animator.SetFloat(PlayerAnimatorIds.MoveZParam, local.z, speedDampTime, Time.deltaTime);
        float rate = fastestClipSpeed > 0f ? Mathf.Max(1f, local.z / fastestClipSpeed) : 1f;
        animator.SetFloat(PlayerAnimatorIds.LocomotionRateParam, rate, speedDampTime, Time.deltaTime);

        // The vault's rate follows its warper: the run-up at the approach's pace, the flight at the
        // rate that keeps the clip's gravity (PlayerVaultState.PlaybackRate)
        if (_parkourStateHash != 0 && _movement.StateMachine.CurrentState == _movement.VaultState)
            animator.SetFloat(PlayerAnimatorIds.ParkourSpeedParam, _movement.VaultState.PlaybackRate);

        // Hit stop: the strike connected and the attacker freezes for a moment (the state, which follows
        // the clip, holds with it)
        animator.speed = IsHitStopped ? 0f : 1f;

        UpdateMatchTargets();
        UpdateStepSmoothing();
    }

    // ─── ICombatAnimation ────────────────────────────────────────────────────────

    /// <summary>Normalized time of the clip of the current attack or hit reaction (−1 if it is not playing yet).</summary>
    public float ActionProgress
    {
        get
        {
            // Until the Animator has run the requested cross-fade, its state info is the previous clip's
            // (the same attack again would read its old 0.97 and end at once)
            if (animator == null || _actionStateHash == 0 || _actionPending) return -1f;
            if (animator.IsInTransition(0))
            {
                AnimatorStateInfo next = animator.GetNextAnimatorStateInfo(0);
                if (next.shortNameHash == _actionStateHash) return next.normalizedTime;
            }
            AnimatorStateInfo current = animator.GetCurrentAnimatorStateInfo(0);
            return current.shortNameHash == _actionStateHash ? current.normalizedTime : -1f;
        }
    }

    public void HitStop(float seconds) => _hitStopUntil = Mathf.Max(_hitStopUntil, Time.time + seconds);

    public bool IsHitStopped => Time.time < _hitStopUntil;

    /// <summary>Cross-fade (s) into an attack: short, the anticipation is part of the clip.</summary>
    private const float AttackCrossFade = 0.06f;

    /// <summary>Cross-fade (s) into a hit reaction: the hit is sudden.</summary>
    private const float HurtCrossFade = 0.05f;

    // ─── IParkourAnimationProgress ───────────────────────────────────────────────

    /// <summary>Normalized time of the current parkour clip (1 once the grab has settled into the hang loop).</summary>
    public float Progress
    {
        get
        {
            if (animator == null || _parkourStateHash == 0) return -1f;
            AnimatorStateInfo current = animator.GetCurrentAnimatorStateInfo(0);
            if (animator.IsInTransition(0))
            {
                AnimatorStateInfo next = animator.GetNextAnimatorStateInfo(0);
                if (next.shortNameHash == _parkourStateHash) return next.normalizedTime;
                if (_parkourStateHash == PlayerAnimatorIds.LedgeGrab && next.shortNameHash == PlayerAnimatorIds.LedgeHang) return 1f;
            }
            if (current.shortNameHash == _parkourStateHash) return current.normalizedTime;
            if (_parkourStateHash == PlayerAnimatorIds.LedgeGrab && current.shortNameHash == PlayerAnimatorIds.LedgeHang) return 1f;
            return -1f;
        }
    }

    /// <summary>Left foot minus right foot along the body's facing (m): which foot leads the stride now.</summary>
    public float FootPhase
    {
        get
        {
            if (_footL == null || _footR == null) return 0f;
            Vector3 d = _footL.position - _footR.position;
            return Vector3.Dot(new Vector3(d.x, 0f, d.z), transform.forward);
        }
    }

    // ─── State → Animation ───────────────────────────────────────────────────────

    private void HandleStateChanged(PlayerState state)
    {
        if (animator == null) return;
        var m = _movement;

        _matchPhase = 0;
        _actionStateHash = ActionStateHash(state);
        _actionPending = _actionStateHash != 0;
        VaultVariant vault = state == m.VaultState ? m.VaultState.Plan.Variant : null;
        _parkourStateHash = vault != null              ? Animator.StringToHash(vault.State)
                          : state == m.MantleState     ? PlayerAnimatorIds.Mantle
                          : state == m.LedgeDropState  ? PlayerAnimatorIds.LedgeDrop
                          : state == m.LedgeGrabState  ? PlayerAnimatorIds.LedgeGrab
                          : state == m.LedgeClimbState ? PlayerAnimatorIds.LedgeClimb
                          : 0;

        if (vault != null)
        {
            // The chosen clip from its entry point (where its run-up is as far from the hand plant as the
            // body is); the warper corrects the root motion from the first frame, also during the fade
            _vaultLength = Mathf.Max(0.01f, vault.Length);
            animator.SetFloat(PlayerAnimatorIds.ParkourSpeedParam, m.VaultState.PlaybackRate);
            animator.CrossFadeInFixedTime(_parkourStateHash, m.VaultState.Plan.CrossFade, 0, m.VaultState.Plan.EntryTime);
        }
        else if (state == m.SlideState)
        {
            // The animation follows the slide: a faster entry drops faster; the slide itself is a true
            // loop that lasts as long as the momentum and the space do
            float speed01 = Mathf.InverseLerp(m.SlideMinEntrySpeed, m.SlideSpeed, m.SlideState.EntrySpeed);
            animator.SetFloat(PlayerAnimatorIds.SlideEnterRateParam, Mathf.Lerp(0.85f, 1.2f, speed01));
            animator.CrossFadeInFixedTime(PlayerAnimatorIds.Slide, fastCrossFadeTime);
        }
        else if (state == m.LedgeGrabState && m.LedgeGrabState.FromDrop)
        {
            // Lowered from the top: the hands already hold the edge, settle into the hang
            _matchPhase = 1;
            animator.CrossFadeInFixedTime(PlayerAnimatorIds.LedgeHang, 0.15f);
        }
        else if (state == m.LedgeGrabState)
        {
            float offset = m.LedgeGrabState.FromGround ? ParkourTimings.GrabGroundStart : ParkourTimings.GrabAirStart;
            animator.CrossFadeInFixedTime(PlayerAnimatorIds.LedgeGrab, fastCrossFadeTime, 0, offset * _grabClipLength);
        }
        else if (_actionStateHash != 0)
        {
            // An attack, from its entry point (a long wind-up is entered later), or a hit reaction. The same
            // clip again right after it (a new chain, a second hit) restarts: the attacks end and start in
            // the guard, so no blend is needed
            AttackData data = state is PlayerAttackState attack ? attack.Data : null;
            float start = data != null ? data.StartAt : 0f;
            float fade = data != null ? AttackCrossFade : HurtCrossFade;
            if (animator.GetCurrentAnimatorStateInfo(0).shortNameHash == _actionStateHash)
                animator.Play(_actionStateHash, 0, start);
            else
                animator.CrossFadeInFixedTime(_actionStateHash, fade, 0, data != null ? start * data.Length : 0f);
        }
        else
        {
            int target = ResolveAnimatorState(state, out float fade);
            if (target != 0)
                animator.CrossFadeInFixedTime(target, fade);
        }

        _previousState = state;
    }

    private int ResolveAnimatorState(PlayerState state, out float fade)
    {
        var m = _movement;
        fade = crossFadeTime;

        if (state == m.IdleState || state == m.RunState)
        {
            // Leaving the guard plays the Ch45 "fight idle → standing idle" transition first
            if (_previousState == m.BlockState) return PlayerAnimatorIds.BlockExit;

            // Leaving the slide gets up from the ground before running
            if (_previousState == m.SlideState) { fade = 0.15f; return PlayerAnimatorIds.SlideExit; }

            // Standing up from a crouch blends straight into the locomotion
            if (_previousState == m.CrouchState) { fade = 0.25f; return PlayerAnimatorIds.Locomotion; }

            // Landing: its weight follows the drop height (Fall → Landing → Recovery → Locomotion)
            if (_previousState == m.FallState && m.LandingSeverity > 0f)
            {
                fade = fastCrossFadeTime;
                if (m.LandedWithRoll) return PlayerAnimatorIds.LandRoll;                                // at speed: roll it out
                if (m.LandingSeverity >= 0.75f) return PlayerAnimatorIds.LandHard;                      // heavy: full absorb
                if (m.LandingSeverity >= 0.35f || state != m.RunState) return PlayerAnimatorIds.Land; // medium: absorb, then go
                return PlayerAnimatorIds.LandRun;                                                       // light: roll into the run
            }

            if (_previousState == m.LedgeClimbState) fade = 0.3f; // crouch on top → stand
            if (_previousState == m.MantleState) fade = 0.2f;     // the mantle ends standing, moving
            return PlayerAnimatorIds.Locomotion;
        }

        if (state == m.CrouchState)      { fade = 0.25f; return PlayerAnimatorIds.Crouch; }
        if (state == m.JumpState)        { fade = 0.1f; return PlayerAnimatorIds.Jump; }
        if (state == m.FallState)
        {
            fade = _previousState == m.LedgeGrabState ? fastCrossFadeTime : fallCrossFadeTime;
            return PlayerAnimatorIds.Fall;
        }
        if (state == m.LedgeClimbState)  { fade = 0.15f; return PlayerAnimatorIds.LedgeClimb; }
        if (state == m.MantleState)      { fade = 0.05f; return PlayerAnimatorIds.Mantle; } // short: the hand match starts right away
        if (state == m.LedgeDropState)   { fade = 0.15f; return PlayerAnimatorIds.LedgeDrop; }
        if (state == m.BlockState)       return PlayerAnimatorIds.BlockEnter;

        if (state == m.DodgeState)
        {
            Vector2 dir = m.DodgeState.LocalDirection;
            animator.SetFloat(PlayerAnimatorIds.DodgeXParam, dir.x);
            animator.SetFloat(PlayerAnimatorIds.DodgeYParam, dir.y);
            fade = 0.05f;
            return PlayerAnimatorIds.Dodge;
        }

        return 0;
    }

    /// <summary>Animator state of an attack (the blow of the chain) or hit reaction, or 0.</summary>
    private int ActionStateHash(PlayerState state)
    {
        var m = _movement;
        if (state == m.LightAttackState)
            return m.LightAttackState.ChainIndex == 1 ? PlayerAnimatorIds.LightAttack1
                 : m.LightAttackState.ChainIndex == 2 ? PlayerAnimatorIds.LightAttack2 : PlayerAnimatorIds.LightAttack3;
        if (state == m.HeavyAttackState) return PlayerAnimatorIds.HeavyAttack;
        if (state == m.HurtState) return m.HurtState.Heavy ? PlayerAnimatorIds.HurtHead : PlayerAnimatorIds.Hurt;
        return 0;
    }

    // ─── Root motion and target matching (parkour) ───────────────────────────────

    /// <summary>
    /// Called by PlayerAnimatorIK.OnAnimatorMove: forwards the clip's motion while a parkour state
    /// drives the body, and turns the body square to the obstacle or wall it is using.
    /// </summary>
    public void ApplyRootMotion()
    {
        if (animator == null) return;
        _actionPending = false; // the Animator has just run: its state info is current

        // An attack's own step: the motor moves the body by it, with collisions (P37)
        if (_movement.StateMachine.CurrentState is PlayerAttackState)
        {
            _movement.QueueActionRootMotion(animator.deltaPosition);
            return;
        }

        if (!_movement.IsRootMotionDriven || _parkourStateHash == 0) return;

        if (_movement.StateMachine.CurrentState == _movement.VaultState)
        {
            // The vault's warper owns the body: it moves it along the clip's measured root path at the
            // clip time (the Animator's own delta follows the root's turning heading, VaultCatalog)
            float n = Progress;
            _movement.VaultState.Warp(n >= 0f ? n * _vaultLength : _movement.VaultState.ClipTime);
            return;
        }

        Quaternion facing = _movement.CurrentLedge.FacingRotation;
        float yaw    = transform.eulerAngles.y;
        float turned = Mathf.MoveTowardsAngle(yaw, facing.eulerAngles.y, parkourTurnSpeed * Time.deltaTime);
        Quaternion turn = Quaternion.Euler(0f, Mathf.DeltaAngle(yaw, turned), 0f);
        // While motion matching fades out under the action (its first 0.06 s), the Animator's delta also
        // carries motion matching's own root motion: its idle drift moved the body up to ~10 cm and the
        // hand's MatchTarget did not account for it (the mantle's palm landed short of the edge). The
        // action's motion starts once motion matching is gone
        bool mxmFading = _movement.Locomotion != null && _movement.Locomotion.Weight > 0f;
        _movement.ApplyRootMotion(mxmFading ? Vector3.zero : animator.deltaPosition,
                                  turn * (mxmFading ? Quaternion.identity : animator.deltaRotation));
    }

    /// <summary>
    /// Queues the MatchTarget phases of the current parkour action, one at a time (Unity discards a
    /// match requested while another is running). Each phase warps the clip's root motion so a body
    /// part reaches a measured point at a measured moment of the clip.
    /// </summary>
    private void UpdateMatchTargets()
    {
        if (_parkourStateHash == 0 || !_movement.IsRootMotionDriven) return;
        if (animator.IsInTransition(0) || animator.isMatchingTarget) return;

        AnimatorStateInfo info = animator.GetCurrentAnimatorStateInfo(0);
        if (info.shortNameHash != _parkourStateHash) return;
        float n = info.normalizedTime;
        var m = _movement;

        if (_parkourStateHash == PlayerAnimatorIds.LedgeGrab && _matchPhase == 0)
        {
            float start = m.LedgeGrabState.FromGround ? ParkourTimings.GrabGroundMatchStart : 0f;
            if (n < start) return;
            Match(AvatarTarget.LeftHand, LeftHandOnLedge(m.CurrentLedge), m.CurrentLedge.FacingRotation, Vector3.one, 0f, n, start, ParkourTimings.GrabHandContact);
        }
        else if (_parkourStateHash == PlayerAnimatorIds.Mantle)
        {
            Quaternion facing = m.CurrentLedge.FacingRotation;
            if (_matchPhase == 0)
            {
                // The supporting hand onto the measured top: corrects both the distance to the edge and
                // a top taller or lower than the clip's 1 m, so the hand plants on the block, not in the air
                Match(AvatarTarget.LeftHand, m.MantleState.HandTarget, facing, Vector3.one, 0f, n, 0f, ParkourTimings.MantleHandMatchEnd);
            }
            else if (_matchPhase == 1 && n >= ParkourTimings.MantleHandRelease)
            {
                // Feet onto the measured stand point on top
                Vector3 stand = m.CurrentLedge.StandPoint + Vector3.up * _rootAboveFeet;
                Match(AvatarTarget.Root, stand, facing, Vector3.one, 0f, n, ParkourTimings.MantleHandRelease, ParkourTimings.MantleStand);
            }
        }
        else if (_parkourStateHash == PlayerAnimatorIds.LedgeDrop && _matchPhase == 0 && n >= ParkourTimings.DropMatchStart)
        {
            // Lowering: the left hand ends on the measured edge
            Match(AvatarTarget.LeftHand, LeftHandOnLedge(m.CurrentLedge), m.CurrentLedge.FacingRotation, Vector3.one, 0f, n, ParkourTimings.DropMatchStart, ParkourTimings.DropHang);
        }
        else if (_parkourStateHash == PlayerAnimatorIds.LedgeClimb && _matchPhase == 0 && n >= ParkourTimings.ClimbMatchStart)
        {
            // Feet onto the stand point on top of the ledge
            Vector3 stand = m.CurrentLedge.StandPoint + Vector3.up * _rootAboveFeet;
            Match(AvatarTarget.Root, stand, m.CurrentLedge.FacingRotation, Vector3.one, 0f, n, ParkourTimings.ClimbMatchStart, ParkourTimings.ClimbStand);
        }
    }

    private void Match(AvatarTarget part, Vector3 position, Quaternion rotation, Vector3 positionWeight, float rotationWeight, float now, float start, float end)
    {
        _matchPhase++;
        if (now >= end) return; // the moment already passed (e.g. a long cross-fade): IK takes over
        animator.MatchTarget(position, rotation, part, new MatchTargetWeightMask(positionWeight, rotationWeight), Mathf.Max(start, now), end);
    }

    /// <summary>Wrist goal of the left hand on a ledge, at the body's lateral position.</summary>
    public static Vector3 LeftHandOnLedge(LedgeInfo ledge, Vector3 bodyPosition)
    {
        Vector3 edge = ledge.EdgeAt(bodyPosition) - ledge.Tangent * ParkourTimings.HandLateral;
        return edge + Vector3.up * ParkourTimings.WristAboveSurface + ledge.Normal * ParkourTimings.WristOutOfFace;
    }

    private Vector3 LeftHandOnLedge(LedgeInfo ledge) => LeftHandOnLedge(ledge, transform.position);

    // ─── Auto step smoothing ─────────────────────────────────────────────────────

    private void HandleStepped(float rise)
    {
        // The body moved up or down the step in one move; the model eases after it, from this very frame
        // (the motor climbs in LateUpdate: waiting for the next Update showed the model up the step for a frame)
        _stepOffset = Mathf.Clamp(_stepOffset - rise, -0.5f, 0.5f);
        if (_model != null) _model.localPosition = _modelBaseLocalPosition + Vector3.up * _stepOffset;
    }

    private void UpdateStepSmoothing()
    {
        if (_model == null) return;
        _stepOffset = Mathf.SmoothDamp(_stepOffset, 0f, ref _stepVelocity, stepSmoothTime);
        if (Mathf.Abs(_stepOffset) < 0.001f) _stepOffset = 0f;
        _model.localPosition = _modelBaseLocalPosition + Vector3.up * _stepOffset;
    }

    // ─── Posture: lean into turns, acceleration and braking ───────────────────────

    /// <summary>
    /// After the animation (and the IK) the torso leans with the body's real acceleration: into a
    /// turn (centripetal acceleration = speed × turn rate), forward when speeding up and back when
    /// braking. Only the spine and chest rotate, so the feet and the pelvis keep their contact. It
    /// fades out in every other state and is off during parkour, where the clip and the contacts rule.
    /// </summary>
    private void LateUpdate()
    {
        if (animator == null || _spine == null || Time.deltaTime <= 0f) return;
        float yawRate = _yawRate, accel = _forwardAccel, forwardSpeed = _forwardSpeed;

        PlayerState s = _movement.StateMachine.CurrentState;
        bool locomotion = (s == _movement.RunState || s == _movement.IdleState) && !_movement.IsRootMotionDriven && _movement.IsGrounded;
        // The lean runs after the IK: in any other state it would move limbs off their contacts
        // (a sliding hand into the floor), so it switches off at once — hidden in the cross-fade
        _leanWeight = locomotion ? Mathf.SmoothDamp(_leanWeight, 1f, ref _leanWeightVel, 0.1f) : 0f;

        float roll  = Mathf.Clamp(-Mathf.Atan2(forwardSpeed * yawRate, 9.81f) * Mathf.Rad2Deg * leanAmount, -maxLeanRoll, maxLeanRoll);
        float pitch = Mathf.Clamp(Mathf.Atan2(accel, 9.81f) * Mathf.Rad2Deg * leanAmount, -maxLeanBack, maxLeanForward);
        _roll  = Mathf.SmoothDamp(_roll, locomotion ? roll : 0f, ref _rollVel, leanSmoothTime);
        _pitch = Mathf.SmoothDamp(_pitch, locomotion ? pitch : 0f, ref _pitchVel, leanSmoothTime);

        float w = _leanWeight;
        if (w >= 0.001f)
        {
            // Split between spine and chest so the back curves instead of bending at one joint
            Quaternion lean = Quaternion.AngleAxis(_roll * w * 0.5f, transform.forward) * Quaternion.AngleAxis(_pitch * w * 0.5f, transform.right);
            _spine.rotation = lean * _spine.rotation;
            if (_chest != null) _chest.rotation = lean * _chest.rotation;
        }

        GuardFeetAboveGround();
        GuardLegsOutOfFace();
        GuardTorsoOffWall();
        GuardHandOffWall(_armL, _handL);
        GuardHandOffWall(_armR, _handR);

        // The strike, on the final pose: the limb the target would feel
        if (s is PlayerAttackState attack)
        {
            Transform limb = Limb(attack.Data.Limb);
            if (limb != null) attack.Sweep(limb.position);
        }
    }

    private Transform Limb(HumanBodyBones bone) =>
        bone == HumanBodyBones.LeftHand ? _handL : bone == HumanBodyBones.RightHand ? _handR :
        bone == HumanBodyBones.LeftFoot ? _footL : bone == HumanBodyBones.RightFoot ? _footR : animator.GetBoneTransform(bone);

    /// <summary>Most the torso guard moves the model in one frame (m).</summary>
    private const float MaxTorsoGuard = 0.25f;

    /// <summary>
    /// On the final pose, outside parkour: a body that bends into a wall in front of it (a landing
    /// right against a block: the clip leans the chest forward ~0.5 m, past the controller's 0.35 m
    /// radius) moves back from the wall for this frame by as much as its head or shoulders would go
    /// in. The legs too, against a wall taller than a step: walking into a block no action fits, a
    /// stride's toes went 3–5 cm into it while motion matching blended over the controller (a curb the
    /// auto step climbs is left alone). Each joint is checked from the capsule's axis at its own
    /// height, which never goes into a wall.
    /// </summary>
    private void GuardTorsoOffWall()
    {
        if (_head == null || _movement.IsRootMotionDriven) return;
        Vector3 push = Vector3.zero;
        float deepest = 0f;
        TorsoJointInWall(_head, HandWallGap, float.MinValue, ref push, ref deepest);
        TorsoJointInWall(_armL, HandWallGap, float.MinValue, ref push, ref deepest);
        TorsoJointInWall(_armR, HandWallGap, float.MinValue, ref push, ref deepest);
        float wallTop = _movement.FeetY + ParkourStandard.StepMaxHeight + 0.05f;
        TorsoJointInWall(_toeL, LegFaceGap, wallTop, ref push, ref deepest);
        TorsoJointInWall(_toeR, LegFaceGap, wallTop, ref push, ref deepest);
        TorsoJointInWall(_kneeL, LegFaceGap, wallTop, ref push, ref deepest);
        TorsoJointInWall(_kneeR, LegFaceGap, wallTop, ref push, ref deepest);
        if (deepest > 0f)
            _model.position += push * Mathf.Min(deepest, MaxTorsoGuard);
    }

    /// <summary>
    /// How far a joint is inside a wall (less than <paramref name="gap"/> from its face) whose top is
    /// above <paramref name="minTop"/>; keeps the deepest in <paramref name="deepest"/> and its push.
    /// </summary>
    private void TorsoJointInWall(Transform joint, float gap, float minTop, ref Vector3 push, ref float deepest)
    {
        if (joint == null) return;
        Vector3 p = joint.position;
        Vector3 axis = new Vector3(transform.position.x, p.y, transform.position.z);
        Vector3 out_ = p - axis;
        float length = out_.magnitude;
        if (length < 0.02f ||
            !Physics.Raycast(axis, out_ / length, out RaycastHit wall, length + gap, _groundMask, QueryTriggerInteraction.Ignore) ||
            Mathf.Abs(wall.normal.y) > 0.5f || wall.collider.bounds.max.y < minTop)
            return;
        float depth = gap - Vector3.Dot(p - wall.point, wall.normal);
        if (depth <= deepest) return;
        deepest = depth;
        push = new Vector3(wall.normal.x, 0f, wall.normal.z).normalized;
    }

    /// <summary>Gap (m) a hand keeps from a wall: the fingers extend past the wrist.</summary>
    private const float HandWallGap = 0.1f;

    /// <summary>
    /// On the final pose, outside parkour and the slide (whose hand rests on the floor): a swinging
    /// hand that ends inside an obstacle (a landing against a wall, a jump next to a block: the
    /// controller keeps the body 0.35 m from a wall, an arm reaches further) turns at the shoulder
    /// until it rests against the wall or on the top it went into. A rule on the final pose and not
    /// an IK goal: while motion matching blends over the controller, the IK pass only reaches part of
    /// the pose (T25).
    /// </summary>
    private void GuardHandOffWall(Transform shoulder, Transform hand)
    {
        if (shoulder == null || hand == null || _movement.IsRootMotionDriven || _movement.StateMachine.CurrentState == _movement.SlideState) return;
        Vector3 reach = hand.position - shoulder.position;
        float length = reach.magnitude;
        if (length < 0.05f ||
            !Physics.Raycast(shoulder.position, reach / length, out RaycastHit hit, length + HandWallGap, _groundMask, QueryTriggerInteraction.Ignore) ||
            hit.normal.y < -0.5f)
            return;
        // A wall: the fingers' gap from its face; a top (or the floor): the wrist on its surface
        float gap = hit.normal.y > 0.5f ? ParkourTimings.WristAboveSurface : HandWallGap;
        float outside = Vector3.Dot(hand.position - hit.point, hit.normal);
        if (outside >= gap) return;
        Vector3 target = hand.position + hit.normal * (gap - outside);
        shoulder.rotation = Quaternion.FromToRotation(reach, target - shoulder.position) * shoulder.rotation;
        HandGuards++;
    }

    /// <summary>Times the hand guard has turned an arm out of a surface (diagnostic for the Play Mode test).</summary>
    public int HandGuards { get; private set; }

    /// <summary>Gap (m) a knee or the toes keep from the block's face while the mantle steps up onto it.</summary>
    private const float LegFaceGap = 0.03f;

    /// <summary>
    /// Mantle, on the final pose: the stepping knee and toes rise into the block's face below its top
    /// (the hand's match leaves the body closer than the clip's own block), so the model moves back
    /// from the face by as much as they would go in, for this frame. The palm stays on the top (it is
    /// planted past the edge); the movement follows the leg, so it eases in and out.
    /// </summary>
    private void GuardLegsOutOfFace()
    {
        if (_kneeL == null || _movement.StateMachine.CurrentState != _movement.MantleState) return;
        LedgeInfo top = _movement.CurrentLedge;
        float back = Mathf.Max(Mathf.Max(InFace(_kneeL, top), InFace(_kneeR, top)), Mathf.Max(InFace(_toeL, top), InFace(_toeR, top)));
        if (back > 0f)
            _model.position += top.Normal * Mathf.Min(back, MaxLegGuard);
    }

    /// <summary>How far (m) a joint is inside the face plane below the top, plus the gap (0 if clear).</summary>
    private static float InFace(Transform joint, LedgeInfo top)
    {
        if (joint == null) return 0f;
        Vector3 p = joint.position;
        if (p.y > top.TopY) return 0f;
        return Mathf.Max(0f, LegFaceGap - Vector3.Dot(p - top.Edge, top.Normal));
    }

    /// <summary>Most the leg guard moves the model in one frame (m).</summary>
    private const float MaxLegGuard = 0.2f;

    /// <summary>
    /// Last line of the contact rules, on the final pose (after the animation, the IK and the lean):
    /// on the ground, a sole never ends below the surface under it. While the Animator blends two
    /// states the IK goals did not always reach the bones (measured on the slide and on landings
    /// that run up stairs), so if a foot is still inside a surface the model rises by that much for
    /// this frame. It never lowers the model and does nothing while parkour drives the body.
    /// </summary>
    private void GuardFeetAboveGround()
    {
        if (_footL == null || _movement.IsRootMotionDriven || !(_movement.IsGrounded || _movement.AirTime < _movement.FallGraceTime))
            return;
        float lift = Mathf.Max(SoleDepth(_footL, animator.leftFeetBottomHeight), SoleDepth(_footR, animator.rightFeetBottomHeight));
        if (lift > 0f)
            _model.position += Vector3.up * Mathf.Min(lift, MaxGroundGuard);
    }

    /// <summary>How deep (m) a sole is inside the surface under it (0 if it is above).</summary>
    private float SoleDepth(Transform foot, float bottomHeight)
    {
        Vector3 p = foot.position;
        if (!Physics.Raycast(p + Vector3.up * 0.5f, Vector3.down, out RaycastHit hit, 1.0f, _groundMask, QueryTriggerInteraction.Ignore) || hit.normal.y < 0.6f)
            return 0f;
        return Mathf.Max(0f, hit.point.y + bottomHeight - p.y);
    }

    /// <summary>Most the ground guard lifts the model in one frame (m): more means something else is wrong.</summary>
    private const float MaxGroundGuard = 0.3f;

    /// <summary>
    /// Turn rate and forward acceleration of the body, measured at the physics rate (smoothed: the
    /// states change the velocity there, and per-frame differences would be spikes and zeros).
    /// </summary>
    private void FixedUpdate()
    {
        float dt = Time.fixedDeltaTime;
        float yaw = transform.eulerAngles.y;
        Vector3 v = _movement.Velocity;
        Vector3 forward = transform.forward;

        float forwardSpeed = Vector3.Dot(new Vector3(v.x, 0f, v.z), forward);
        _yawRate      = Mathf.Lerp(_yawRate, Mathf.DeltaAngle(_lastYaw, yaw) * Mathf.Deg2Rad / dt, 0.5f);
        _forwardAccel = Mathf.Lerp(_forwardAccel, (forwardSpeed - _lastForwardSpeed) / dt, 0.5f);
        _forwardSpeed = forwardSpeed;
        _lastYaw = yaw;
        _lastForwardSpeed = forwardSpeed;
    }

    /// <summary>Current torso lean (degrees: roll into the turn, pitch forward) for tests.</summary>
    public Vector2 Lean => new Vector2(_roll * _leanWeight, _pitch * _leanWeight);

    // ─── IK (called by PlayerAnimatorIK on the model) ────────────────────────────

    /// <summary>Hands and feet contact (PlayerContactIK).</summary>
    public void ApplyIK()
    {
        if (animator == null) return;
        if (_contactIK != null) _contactIK.Solve(animator);
    }
}
